apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: myweatherhub
  name: myweatherhub
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: myweatherhub
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: myweatherhub
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: myweatherhub
        image: '{{ .Values.images.myweatherhub }}'
        imagePullPolicy: Always
        name: myweatherhub
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180